### PR TITLE
docker: clean up the Dockerfile and speed up the build

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- update memkind version in installation script,
- make use of all cores while compiling all libs,
- remove redundant packages (mostly required for ndctl (?) ),
- remove redundant steps and comments,
- including removal of JNI, which is now built-in within Java binding.

---
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/2)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/2)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @janekmi)

___
*[docker/Dockerfile, line 65 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/2#-MkgXpqh3gNOG06k_IFI:-MkgXpqh3gNOG06k_IFJ:b-yw7x4l) ([raw file](https://github.com/pmemhackathon/2021-04-21.web/blob/55b8681b202b26553f1ec38ba9f32cd84f871703/docker/Dockerfile#L65)):*
FYI

> Node.js 10.x is no longer actively supported!

**Comment by ldorau** [comment]
This PR fixes https://github.com/pmemhackathon/2021-04-21.web/issues/7

**Review by ldorau — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/2#-:-MkkaeeK5NbPtnN7rgX3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
@andyrudoff, can you please take a look and pull this in? If everything is alright, of course

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/2#-:-MkqaCHp4G9vTKMNmPYC:bjf0t5y)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[docker/Dockerfile, line 65 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/2#-MkgXpqh3gNOG06k_IFI:-Mkq_XGQCCdEj4QLm8hs:b-ms5iaj) ([raw file](https://github.com/pmemhackathon/2021-04-21.web/blob/55b8681b202b26553f1ec38ba9f32cd84f871703/docker/Dockerfile#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

FYI

> Node.js 10.x is no longer actively supported!
</blockquote></details>

tbh, I'm not sure why the installation of nodejs was done this way, so I didn't touch it :wink:

**Comment by lukaszstolarczuk** [comment]
Continued in https://github.com/pmemhackathon/2021-04-21.web/pull/2

**Pull request closed without merging**
