### PR TITLE
example B: update Web description and steps

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
matching updated code, in:
https://github.com/pmemhackathon/2021-04-21/pull/2

### !! Disclaimer: I didn't test it on the server environment !!
I hope someone with a server already set up, could test it for me 😃 🙏

---
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/3)

### CODE REVIEW

**Comment by janekmi** [comment]
Do you have any instructions on how to run the server on-premises?

**Comment by lukaszstolarczuk** [comment]
> Do you have any instructions on how to run the server on-premises?

there's `doc` dir, but the instructions didn't look complete...? (https://github.com/pmemhackathon/2021-04-21.web/tree/master/doc)

**Comment by janekmi** [comment]
```
[running make java...]
make -C PmemkvExample java
make[1]: Entering directory '/home/pmemuser1/2021-04-21/examples/B/PmemkvExample'
mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< io.pmem:PmemkvExample >------------------------
[INFO] Building PmemkvExample 1.2.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.pmem:pmemkv:jar:1.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.268 s
[INFO] Finished at: 2021-09-24T06:41:24-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project PmemkvExample: Could not resolve dependencies for project io.pmem:PmemkvExample:jar:1.2.0: Failure to find io.pmem:pmemkv:jar:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
make[1]: *** [Makefile:6: java] Error 1
make[1]: Leaving directory '/home/pmemuser1/2021-04-21/examples/B/PmemkvExample'
make: *** [Makefile:18: java] Error 2

make java: exit status 2
```

**Comment by lukaszstolarczuk** [comment]
Thanks @janekmi . I've added a small update in the code, but now I think there's something wrong with the docker.

I will update soon-ish the image (https://github.com/pmemhackathon/2021-04-21.web/pull/2) with dependencies - to go offline and make sure the pmemkv-java installation is correct.

**Comment by lukaszstolarczuk** [comment]
continued on new repo: https://github.com/pmemhackathon/hackathon.web/pull/8

**Pull request closed without merging**
