### PR TITLE
example R: add the librpma example

### PR DESCRIPTION
**Pull request by ldorau**
In this example we want to introduce to you a basic way of accessing
Persistent Memory when it is installed in a remote system.
Remote Persistent Memory (or RPMem for short) is a way of doing this
via a network by making use of the Remote Direct Memory Access (RDMA)
technology.

This example is an introduction to RPMem. We will guide you briefly through
setting up all required hardware and software components and verifying whether
the connection works properly. Having that, we will show you how to access
Persistent Memory on a remote system using the librpma library.

After completing this example you will know:
- what is RPMem and what it is good for,
- how RPMem is different comparing to PMem,
- what hardware and software components are required to start using RPMem,
- how to verify whether the RDMA network works properly,
- how to use librpma API to:
- establish a connection,
- prepare memory for remote manipulation,
- manipulate memory on the remote system,
- assure persistency of stores to the remote system.

Step-by-step you will:
- test the connection on the basic level using ping,
- test the connection RDMA capabilities using rping,
- review an application focusing on establishing a connection,
- review an application reading remote system's memory and writing it back
  in the persistent manner.

Co-authored-by: Oksana Salyk <oksana.salyk@intel.com>
Co-authored-by: Jan M Michalski <jan.m.michalski@intel.com>
Co-authored-by: Patryk717 <patrykzbierski717@wp.pl>

Signed-off-by: Lukasz Dorau <lukasz.dorau@intel.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-:-NAxbGuG0FjUswyEHcw6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`docker/librpma.sh` line 14 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-NBBPHhc4fz-IfPUtPlo:-NBBPHhd02OgmtQSDQr6:b-xess0s) ([raw file](https://github.com/pmemhackathon/2021-04-21.web/blob/e516fd0edb7c1214b71f3bb0ba2c40f34afdb4db/docker/librpma.sh#L14)):*
> ```Shell
> mkdir -p rpma-${LIBRPMA_VERSION}/build
> cd rpma-${LIBRPMA_VERSION}/build
> cmake .. -DCMAKE_BUILD_TYPE=Debug \
> ```

Shall we use the Release version in a hackathon?



_Suggestion:_
```Shell
Release
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`docker/librpma.sh` line 14 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-NBBPHhc4fz-IfPUtPlo:-NBBb4wo7xiQlWr7QnQX:bd2zv4c) ([raw file](https://github.com/pmemhackathon/2021-04-21.web/blob/e516fd0edb7c1214b71f3bb0ba2c40f34afdb4db/docker/librpma.sh#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we use the Release version in a hackathon?
</blockquote></details>

I think the Debug version is better in case of debugging.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`docker/librpma.sh` line 14 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-NBBPHhc4fz-IfPUtPlo:-NBBnN5P8dLiqL8BfZgJ:bmdzioz) ([raw file](https://github.com/pmemhackathon/2021-04-21.web/blob/e516fd0edb7c1214b71f3bb0ba2c40f34afdb4db/docker/librpma.sh#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think the Debug version is better in case of debugging.
</blockquote></details>

Do we debug examples during hackathon?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`docker/librpma.sh` line 14 at r1](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-NBBPHhc4fz-IfPUtPlo:-NBBqa0hDODJ-NhFxekD:bi8e5pj) ([raw file](https://github.com/pmemhackathon/2021-04-21.web/blob/e516fd0edb7c1214b71f3bb0ba2c40f34afdb4db/docker/librpma.sh#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we debug examples during hackathon?
</blockquote></details>

A user may need to debug their code.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-:-NBCW_Rq4JrndUY1PM1T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@igchor please review and merge ;-)

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-:-NBCZ1EKBVXXb7US_dV6:b22qbjp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by igchor — COMMENTED** [review]
LGTM but when I tried to run it (using create_pmemusers and then enable_pmemusers) I got: `enable_pmemusers: ERROR: config_softroce.sh failed: Error: cannot find the 'rdma_rxe' module in the '/lib/modules/5.14.0-142.el9.x86_64' directory` (I rebuild the image to have all the packages you added).

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-:-NBJEnPc-2QWlUjDzTHJ:bf7osmy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by igchor — COMMENTED** [review]
Ok, I probably don;t have all the necessary things installed/configured on the host. Could you please extend: https://github.com/pmemhackathon/2021-04-21.web/blob/master/doc/Install-CentOS8 and describe what is needed for the rpma example? (I noticed that /dev/dax is required - it would be good to put that into the doc as well).

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-:-NBJWaSq2toJeBefBc-T:bv544hf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@igchor Done

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-:-NBMmff57GPaXYPu4rih:b-4zc7z3)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by igchor — COMMENTED** [review]
Thanks, I have just created a separate repo: https://github.com/pmemhackathon/hackathon.web Could you please make a PR against it? Idea is to add all new changes there and perhaps make some tags/branches for particular hackathons.

Also would you be able to enable the rpma example optionally (only when some flag is passed to enable_pmemusers or something like this)? Some of the machines I have from SNIA to host the hackathon do not have correct kernel and it would be good to be able to run other examples anyway.

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/2021-04-21.web/8#-:-NBPmqBQ65jgLW_iySk6:b-u3xhsp)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Comment by ldorau** [comment]
Replaced with https://github.com/pmemhackathon/hackathon.web/pull/3

**Pull request closed without merging**
